name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x bycomvpn2.1/gradlew

    - name: Build with Gradle
      run: cd bycomvpn2.1 && ./gradlew assembleDebug # Or assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: bycomvpn2.1/app/build/outputs/apk/debug/app-debug.apk # Adjust path as needed
